sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.1.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.10.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.11.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.12.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.13.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.14.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.15.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.16.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.17.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.18.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.19.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.2.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.20.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.21.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.22.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.23.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.24.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.25.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.26.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.27.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.28.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.29.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.3.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.4.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.5.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.6.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.7.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.8.sing.maf
sh split.sh /public/home/liuchang/projects/giraffe/01.HCE/splitmaf/goat.9.sing.maf
