/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.1.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.1.sing.bed.maf splitmaf/goat.1.sing.maf
#/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.2.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.2.sing.bed.maf splitmaf/goat.2.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.3.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.3.sing.bed.maf splitmaf/goat.3.sing.maf
#/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.4.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.4.sing.bed.maf splitmaf/goat.4.sing.maf
#/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.5.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.5.sing.bed.maf splitmaf/goat.5.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.6.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.6.sing.bed.maf splitmaf/goat.6.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.7.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.7.sing.bed.maf splitmaf/goat.7.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.8.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.8.sing.bed.maf splitmaf/goat.8.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.9.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.9.sing.bed.maf splitmaf/goat.9.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.10.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.10.sing.bed.maf splitmaf/goat.10.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.11.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.11.sing.bed.maf splitmaf/goat.11.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.12.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.12.sing.bed.maf splitmaf/goat.12.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.13.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.13.sing.bed.maf splitmaf/goat.13.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.14.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.14.sing.bed.maf splitmaf/goat.14.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.15.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.15.sing.bed.maf splitmaf/goat.15.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.16.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.16.sing.bed.maf splitmaf/goat.16.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.17.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.17.sing.bed.maf splitmaf/goat.17.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.18.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.18.sing.bed.maf splitmaf/goat.18.sing.maf
#/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.19.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.19.sing.bed.maf splitmaf/goat.19.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.20.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.20.sing.bed.maf splitmaf/goat.20.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.21.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.21.sing.bed.maf splitmaf/goat.21.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.22.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.22.sing.bed.maf splitmaf/goat.22.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.23.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.23.sing.bed.maf splitmaf/goat.23.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.24.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.24.sing.bed.maf splitmaf/goat.24.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.25.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.25.sing.bed.maf splitmaf/goat.25.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.26.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.26.sing.bed.maf splitmaf/goat.26.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.27.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.27.sing.bed.maf splitmaf/goat.27.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.28.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.28.sing.bed.maf splitmaf/goat.28.sing.maf
/home/yinyuan/scripts/ucsc_tools/mafsInRegion ELEMENTS/goat.29.noGiraffe.sing.maf.bed.new.bed splitmaf/goat.29.sing.bed.maf splitmaf/goat.29.sing.maf
