python 20.get_uniq.inallruminant.py splitmaf/goat.19.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.2.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.4.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.5.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.1.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.3.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.6.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.7.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.8.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.9.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.10.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.11.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.12.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.13.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.14.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.15.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.16.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.17.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.18.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.20.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.21.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.22.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.23.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.24.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.25.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.26.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.27.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.28.sing.bed.maf
python 20.get_uniq.inallruminant.py splitmaf/goat.29.sing.bed.maf
